version: "3.9"
services:
  web-dev-nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/www/data:ro
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 1G
        reservations:
          memory: 128M 
  web-dev-postgres:
    build: 
      context: ./db
      dockerfile: DockerFile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thankyoushayan
      - POSTGRES_DB=webdev
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 1G
        reservations:
          memory: 128M
  web-dev-redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 1G
        reservations:
          memory: 128M 