version: "3.9"
services:
  web-dev-nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  web-dev-postgres:
    build: 
      context: ./db
      dockerfile: DockerFile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thankyoushayan
      - POSTGRES_DB=webdev
  web-dev-redis:
    image: redis:6.0.8
