version: "3.9"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  notes-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notes
      - POSTGRES_DB=notes
